;;; -*- lexical-binding: t -*-
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   '("dd4582661a1c6b865a33b89312c97a13a3885dc95992e2e5fc57456b4c545176" default))
 '(org-agenda-files
   '("~/notes/org/daily/2026-02-28.org"
     "/home/gardner/notes/org/20260222201353-javascript_design_patterns.org"
     "/home/gardner/notes/org/20260222202808-programming_languages.org"
     "/home/gardner/notes/org/20260222203214-c.org"
     "/home/gardner/notes/org/20260222203634-something.org"
     "/home/gardner/notes/org/20260222203654-python.org"
     "/home/gardner/notes/org/20260222204707-c.org"
     "/home/gardner/notes/org/20260225135526-trem.org"
     "/home/gardner/notes/org/20260227003321-raytracing.org"
     "/home/gardner/notes/org/20260227141230-alergia.org"
     "/home/gardner/notes/org/20260227141247-alergia.org"
     "/home/gardner/notes/org/20260227141333-sometihng_else.org"
     "/home/gardner/notes/org/@RFC9315.md.org"
     "/home/gardner/notes/org/Alergia.md.org"
     "/home/gardner/notes/org/Arrumando a casa.md.org"
     "/home/gardner/notes/org/Baróvia.md.org"
     "/home/gardner/notes/org/Bolo de cenoura.md.org"
     "/home/gardner/notes/org/Bolo simples.md.org"
     "/home/gardner/notes/org/Bugs in writing A guide to debugging your prose - Lyn Dupre.md.org"
     "/home/gardner/notes/org/Capítulo 1 - Nas Brumas.md.org"
     "/home/gardner/notes/org/Capítulo 2 - As Terras de Baróvia.md.org"
     "/home/gardner/notes/org/Capítulo 3 - A Vila de Baróvia.md.org"
     "/home/gardner/notes/org/Capítulo 9 - Passagem Tsolenka.md.org"
     "/home/gardner/notes/org/Carniçais.md.org"
     "/home/gardner/notes/org/Casa da morte - Sotão.md.org"
     "/home/gardner/notes/org/Clube do livro.md.org"
     "/home/gardner/notes/org/Coffee-break puzzles.md.org"
     "/home/gardner/notes/org/Comprehensive_survey_on_SmartNICs_1722531964091_0.pdf.md.org"
     "/home/gardner/notes/org/Computer Networks - CMP182.md.org"
     "/home/gardner/notes/org/Computer Systems Security - CMP 230.md.org"
     "/home/gardner/notes/org/Conferences and Journals.md.org"
     "/home/gardner/notes/org/Copper - Colorscheme.md.org"
     "/home/gardner/notes/org/Curse of Strahd.md.org"
     "/home/gardner/notes/org/D&De5.md.org"
     "/home/gardner/notes/org/Damn Vulnerable Graphql.md.org"
     "/home/gardner/notes/org/DnDe5.md.org"
     "/home/gardner/notes/org/Elisabeth Durst.md.org"
     "/home/gardner/notes/org/Exaustão.md.org"
     "/home/gardner/notes/org/Fantasma.md.org"
     "/home/gardner/notes/org/Farma Eleganti.md.org"
     "/home/gardner/notes/org/Fuzzy Match - Relatório.md.org"
     "/home/gardner/notes/org/GTER.md.org" "/home/gardner/notes/org/GTS.md.org"
     "/home/gardner/notes/org/Game Boy Coding Adventure - Maximilien Dagois.md.org"
     "/home/gardner/notes/org/Get Things Done - David Allen.md.org"
     "/home/gardner/notes/org/Grick.md.org"
     "/home/gardner/notes/org/Gustav Durst.md.org"
     "/home/gardner/notes/org/Hilda - Colorscheme.md.org"
     "/home/gardner/notes/org/How to refactor.md.org"
     "/home/gardner/notes/org/IX fórum 2025.md.org"
     "/home/gardner/notes/org/Inbox.md.org"
     "/home/gardner/notes/org/Intent-based networking.md.org"
     "/home/gardner/notes/org/International Journal Network Management - Review.md.org"
     "/home/gardner/notes/org/Internet Exchange Points.md.org"
     "/home/gardner/notes/org/Introdução à Comunicação Científica - CMP176.md.org"
     "/home/gardner/notes/org/Jade - Colorscheme.md.org"
     "/home/gardner/notes/org/Jupyter Notebooks.md.org"
     "/home/gardner/notes/org/Kildra.md.org"
     "/home/gardner/notes/org/Lab Determine the number of columns.md.org"
     "/home/gardner/notes/org/Lab Find Column Containing Text.md.org"
     "/home/gardner/notes/org/Lab Login Bypass.md.org"
     "/home/gardner/notes/org/Lab Retrieve Data From Other Tables.md.org"
     "/home/gardner/notes/org/Lab Retrive Hidden Data.md.org"
     "/home/gardner/notes/org/Level 0.md.org"
     "/home/gardner/notes/org/Level 1.md.org"
     "/home/gardner/notes/org/Level 10.md.org"
     "/home/gardner/notes/org/Level 11.md.org"
     "/home/gardner/notes/org/Level 12.md.org"
     "/home/gardner/notes/org/Level 13.md.org"
     "/home/gardner/notes/org/Level 14.md.org"
     "/home/gardner/notes/org/Level 15.md.org"
     "/home/gardner/notes/org/Level 16.md.org"
     "/home/gardner/notes/org/Level 17.md.org"
     "/home/gardner/notes/org/Level 18.md.org"
     "/home/gardner/notes/org/Level 19.md.org"
     "/home/gardner/notes/org/Level 2.md.org"
     "/home/gardner/notes/org/Level 20.md.org"
     "/home/gardner/notes/org/Level 21.md.org"
     "/home/gardner/notes/org/Level 22.md.org"
     "/home/gardner/notes/org/Level 23.md.org"
     "/home/gardner/notes/org/Level 24.md.org"
     "/home/gardner/notes/org/Level 25.md.org"
     "/home/gardner/notes/org/Level 26.md.org"
     "/home/gardner/notes/org/Level 27.md.org"
     "/home/gardner/notes/org/Level 28.md.org"
     "/home/gardner/notes/org/Level 29.md.org"
     "/home/gardner/notes/org/Level 3.md.org"
     "/home/gardner/notes/org/Level 30.md.org"
     "/home/gardner/notes/org/Level 31.md.org"
     "/home/gardner/notes/org/Level 32.md.org"
     "/home/gardner/notes/org/Level 33.md.org"
     "/home/gardner/notes/org/Level 4.md.org"
     "/home/gardner/notes/org/Level 5.md.org"
     "/home/gardner/notes/org/Level 6.md.org"
     "/home/gardner/notes/org/Level 7.md.org"
     "/home/gardner/notes/org/Level 8.md.org"
     "/home/gardner/notes/org/Level 9.md.org"
     "/home/gardner/notes/org/Lil' Meg.md.org"
     "/home/gardner/notes/org/Livro do jogador.md.org"
     "/home/gardner/notes/org/Maena.md.org"
     "/home/gardner/notes/org/Making notes about Research Papers.md.org"
     "/home/gardner/notes/org/Making science.md.org"
     "/home/gardner/notes/org/Managing (en-US).md.org"
     "/home/gardner/notes/org/Mansão Durst - Primeiro andar.md.org"
     "/home/gardner/notes/org/Mansão Durst - Segundo andar.md.org"
     "/home/gardner/notes/org/Mansão Durst - Terceiro andar.md.org"
     "/home/gardner/notes/org/Mansão Durst.md.org"
     "/home/gardner/notes/org/Margareth.md.org"
     "/home/gardner/notes/org/MeshAgent-Enabling Reliable Network Management with Large Language Models.md.org"
     "/home/gardner/notes/org/Misc.md.org" "/home/gardner/notes/org/Mofo.md.org"
     "/home/gardner/notes/org/Mímico.md.org"
     "/home/gardner/notes/org/NOMS.md.org"
     "/home/gardner/notes/org/Network Telescopes.md.org"
     "/home/gardner/notes/org/Nota de suicídio de Gustav.md.org"
     "/home/gardner/notes/org/Névoa.md.org"
     "/home/gardner/notes/org/O Processo - Franz Kafka.md.org"
     "/home/gardner/notes/org/On Large Language Models.md.org"
     "/home/gardner/notes/org/On writing.md.org"
     "/home/gardner/notes/org/Overcoming the Knowledge Gap.md.org"
     "/home/gardner/notes/org/PhD How to write a great research paper (video).md.org"
     "/home/gardner/notes/org/Planejar.md.org"
     "/home/gardner/notes/org/Plano de refeição.md.org"
     "/home/gardner/notes/org/Plano de treino.md.org"
     "/home/gardner/notes/org/Poison.md.org"
     "/home/gardner/notes/org/Porão - 1.md.org"
     "/home/gardner/notes/org/Quais livros ler.md.org"
     "/home/gardner/notes/org/Ravena.md.org"
     "/home/gardner/notes/org/Redes de Feistel.md.org"
     "/home/gardner/notes/org/Reunião-06-08-2024.md.org"
     "/home/gardner/notes/org/Reunião-30-07-2024.md.org"
     "/home/gardner/notes/org/Rose.md.org"
     "/home/gardner/notes/org/Rosna ee.md.org"
     "/home/gardner/notes/org/Self Discipline Struthless Video.md.org"
     "/home/gardner/notes/org/Seminary - CMP182.md.org"
     "/home/gardner/notes/org/Sharp Axe method struthless.md.org"
     "/home/gardner/notes/org/Sites de receitas.md.org"
     "/home/gardner/notes/org/Sql Injection.md.org"
     "/home/gardner/notes/org/Sql Union Attacks.md.org"
     "/home/gardner/notes/org/Sqli Labs.md.org"
     "/home/gardner/notes/org/Sqli Logs.md.org"
     "/home/gardner/notes/org/Strahd von Zarovich.md.org"
     "/home/gardner/notes/org/Strahd.md.org"
     "/home/gardner/notes/org/TIME MANAGEMENT GUIDE for busy but lazy people.md.org"
     "/home/gardner/notes/org/Tasks.md.org"
     "/home/gardner/notes/org/Technical debt.md.org"
     "/home/gardner/notes/org/Testing.md.org"
     "/home/gardner/notes/org/The Unworthy - Agustina Bazterrica.md.org"
     "/home/gardner/notes/org/Thorn.md.org"
     "/home/gardner/notes/org/Tico Mia Santos.md.org"
     "/home/gardner/notes/org/Tobi.md.org"
     "/home/gardner/notes/org/Understanding SmartNICS - A Deep Dive into NVIDIA Bluefield-2 Technology.md.org"
     "/home/gardner/notes/org/Urucum - Colorscheme.md.org"
     "/home/gardner/notes/org/Vida financeira.md.org"
     "/home/gardner/notes/org/Video About OpenMP.md.org"
     "/home/gardner/notes/org/Visualização de Informações - CMP264.md.org"
     "/home/gardner/notes/org/Web Hacking.md.org"
     "/home/gardner/notes/org/Writing Scientific Papers.md.org"
     "/home/gardner/notes/org/Xadrez.md.org"
     "/home/gardner/notes/org/adhd.md.org"
     "/home/gardner/notes/org/animes.md.org"
     "/home/gardner/notes/org/application.md.org"
     "/home/gardner/notes/org/armadura animada.md.org"
     "/home/gardner/notes/org/bash.md.org"
     "/home/gardner/notes/org/books.md.org"
     "/home/gardner/notes/org/callouts.md.org"
     "/home/gardner/notes/org/campanha de D&De5.md.org"
     "/home/gardner/notes/org/chatbot.md.org"
     "/home/gardner/notes/org/checkmarks.md.org"
     "/home/gardner/notes/org/contato@operaprodutora.com.br.md.org"
     "/home/gardner/notes/org/cool-links.md.org"
     "/home/gardner/notes/org/cypher-breaker.md.org"
     "/home/gardner/notes/org/ddogg.md.org"
     "/home/gardner/notes/org/design-patterns.org"
     "/home/gardner/notes/org/design.md.org"
     "/home/gardner/notes/org/diffie-hellman.md.org"
     "/home/gardner/notes/org/drill.md.org"
     "/home/gardner/notes/org/eat-that-frog.md.org"
     "/home/gardner/notes/org/errc-2024.md.org"
     "/home/gardner/notes/org/espectro.md.org"
     "/home/gardner/notes/org/feeds.md.org"
     "/home/gardner/notes/org/finishing-is-a-problem.md.org"
     "/home/gardner/notes/org/ghasts.md.org"
     "/home/gardner/notes/org/ghouls.md.org"
     "/home/gardner/notes/org/gunicorn.md.org"
     "/home/gardner/notes/org/home-cleaning.md.org"
     "/home/gardner/notes/org/how to live 24 hours a Day.md.org"
     "/home/gardner/notes/org/journal.org"
     "/home/gardner/notes/org/journalling.md.org"
     "/home/gardner/notes/org/livro do mestre.md.org"
     "/home/gardner/notes/org/lívido.md.org"
     "/home/gardner/notes/org/markup.md.org"
     "/home/gardner/notes/org/masters.md.org"
     "/home/gardner/notes/org/netscope.md.org"
     "/home/gardner/notes/org/obsidian.md.org"
     "/home/gardner/notes/org/openmp.md.org"
     "/home/gardner/notes/org/recon.md.org"
     "/home/gardner/notes/org/regras.md.org"
     "/home/gardner/notes/org/rsa.md.org" "/home/gardner/notes/org/rust.md.org"
     "/home/gardner/notes/org/sistemas.md.org"
     "/home/gardner/notes/org/smartix.md.org"
     "/home/gardner/notes/org/software.md.org"
     "/home/gardner/notes/org/todo.org"
     "/home/gardner/notes/org/um-dia-perfeito.md.org"
     "/home/gardner/notes/org/wargames.md.org"
     "/home/gardner/notes/org/webtesting-checklist-recon.md.org"
     "/home/gardner/notes/org/writing-for-computer-science.md.org"
     "/home/gardner/notes/org/writing.md.org"
     "/home/gardner/notes/org/玄德.md.org"))
 '(warning-suppress-types '((treesit) (defvaralias) (lexical-binding))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
(put 'narrow-to-region 'disabled nil)
