# ~/.config/alacritty/alacritty.toml
[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]
size = 12.0

[font.bold]
family = "More Perfect DOS VGA"
style = "Bold"

[font.bold_italic]
family = "More Perfect DOS VGA"
style = "Bold Italic"

[font.italic]
family = "More Perfect DOS VGA"
style = "Italic"

[font.normal]
family = "More Perfect DOS VGA"
style = "Regular"
