# ~/.config/alacritty/alacritty.toml
[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]
size = 12.0

[font.bold]
family = "More Perfect DOS VGA"
style = "Bold"

[font.bold_italic]
family = "More Perfect DOS VGA"
style = "Bold Italic"

[font.italic]
family = "More Perfect DOS VGA"
style = "Italic"

[font.normal]
family = "More Perfect DOS VGA"
style = "Regular"

# Colors (Alabaster)
# author tonsky

[colors.primary]
background = '#F7F7F7'
foreground = '#434343'

[colors.cursor]
text = '#F7F7F7'
cursor = '#434343'

[colors.normal]
black = '#000000'
red = '#AA3731'
green = '#448C27'
yellow = '#CB9000'
blue = '#325CC0'
magenta = '#7A3E9D'
cyan = '#0083B2'
white = '#BBBBBB'

[colors.bright]
black = '#777777'
red = '#F05050'
green = '#60CB00'
yellow = '#FFBC5D'
blue = '#007ACC'
magenta = '#E64CE6'
cyan = '#00AACB'
white = '#FFFFFF'
